### ISSUE TITLE
Tratar mensagens de canais

### ISSUE THREAD

**Issue by iuriguilherme** [matehackers/matebot#65]
Mensagens enviadas para os canais (anônimos) onde os bots estão levantam uma exceção porque os bots estão tentando obter o **from_id** que obviamente não existe na update.

Toda update no entanto tem (ou deveria ter, confirmar) um atributo "type" que pode ser "channel".

```
2020-09-01 18:59:48,163 - telegram.ext.dispatcher - ERROR - An error was raised while processing the update and an uncaught error was raised while handling the error with an error_handler
Traceback (most recent call last):
  File "/home/iuri/git/matehackers/matebot/matebot/ptb_matebot/controllers.py", line 132, in error_callback                                      
    raise context.error
  File "/home/iuri/.local/share/virtualenvs/matebot-OupDHXVR/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 340, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/iuri/.local/share/virtualenvs/matebot-OupDHXVR/lib/python3.7/site-packages/telegram/ext/handler.py", line 119, in handle_update    
    return self.callback(update, context)
  File "/home/iuri/git/matehackers/matebot/matebot/ptb_matebot/controllers.py", line 277, in x9_callback                                         
    update_text(update,text)
  File "/home/iuri/git/matehackers/matebot/matebot/ptb_matebot/controllers.py", line 111, in update_text                                         
    update.effective_user.__dict__.items()
AttributeError: 'NoneType' object has no attribute '__dict__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/iuri/.local/share/virtualenvs/matebot-OupDHXVR/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 353, in process_update
    self.dispatch_error(update, e)
  File "/home/iuri/.local/share/virtualenvs/matebot-OupDHXVR/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 522, in dispatch_error
    callback(update, CallbackContext.from_error(update, error, self))
  File "/home/iuri/git/matehackers/matebot/matebot/ptb_matebot/controllers.py", line 205, in error_callback                                      
    update_text(update,text)
  File "/home/iuri/git/matehackers/matebot/matebot/ptb_matebot/controllers.py", line 111, in update_text                                         
    update.effective_user.__dict__.items()
AttributeError: 'NoneType' object has no attribute '__dict__'
```

**Comment by iuriguilherme** [comment]
No Aiogram tem handlers pra publicações em canais que estão funcionando em todos bots em **v0.1.6.11** bdf42611dc69cb350c69be3b10fc0647e992a266
